name = "femtolens-api"
main = "src/index.js"
compatibility_date = "2024-09-01"

[vars]
CORS_ORIGIN = "*"
AI_PROVIDER = "groq"
GOOGLE_CLIENT_ID = "63932542306-n27pfddhat5po84e8l0kuq2i7rama4no.apps.googleusercontent.com"
account_id = "ab2ac3186ce21fac97dff24ea4ff13fe"

[[d1_databases]]
binding = "DB"
database_name = "femtolens-db"
database_id = "cb071481-ed33-4075-a598-624b7dd046d9"
NCBI_API_KEY = "40e5399046303596d6b0d589be55fb054e08"
